#!/usr/bin/env bash
#
# Walks the Proxmox host over SSH, lists every VM and LXC, and writes a
# terraform `import` block per existing guest into imports.tf.
#
# Usage:
#   ./scripts/generate-imports.sh           # uses values.tfvars defaults
#   PVE_SSH_HOST=10.0.0.40 ./scripts/generate-imports.sh
#
# After this runs:
#   terraform plan \
#     -var-file=/home/raman/git/home-lab/.lab/hypervisor/proxmox/values.tfvars \
#     -generate-config-out=generated.tf

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE_DIR="$(dirname "$SCRIPT_DIR")"
IMPORTS_FILE="$MODULE_DIR/imports.tf"

PVE_SSH_HOST="${PVE_SSH_HOST:-}"
PVE_SSH_USER="${PVE_SSH_USER:-root}"
PVE_NODE_NAME="${PVE_NODE_NAME:-}"

if [[ -z "$PVE_SSH_HOST" ]]; then
  echo "PVE_SSH_HOST is not set. Export it or pass on the command line." >&2
  echo "Example: PVE_SSH_HOST=10.0.0.40 ./scripts/generate-imports.sh" >&2
  exit 1
fi

if [[ -z "$PVE_NODE_NAME" ]]; then
  PVE_NODE_NAME="$(ssh "$PVE_SSH_USER@$PVE_SSH_HOST" hostname -s)"
fi

echo "Listing guests on $PVE_NODE_NAME via ssh $PVE_SSH_USER@$PVE_SSH_HOST..."

VMS="$(ssh "$PVE_SSH_USER@$PVE_SSH_HOST" 'qm list | awk "NR>1 {print \$1\":\"\$2}"' || true)"
LXCS="$(ssh "$PVE_SSH_USER@$PVE_SSH_HOST" 'pct list | awk "NR>1 {print \$1\":\"\$3}"' || true)"

{
  echo "// Generated by scripts/generate-imports.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "// PVE node: $PVE_NODE_NAME"
  echo ""

  if [[ -n "$VMS" ]]; then
    while IFS=: read -r vmid name; do
      [[ -z "$vmid" ]] && continue
      slug="$(echo "$name" | tr -c 'A-Za-z0-9_' '_' | sed 's/__*/_/g; s/^_//; s/_$//')"
      echo "import {"
      echo "  to = proxmox_virtual_environment_vm.${slug}"
      echo "  id = \"${PVE_NODE_NAME}/${vmid}\""
      echo "}"
      echo ""
    done <<<"$VMS"
  fi

  if [[ -n "$LXCS" ]]; then
    while IFS=: read -r vmid name; do
      [[ -z "$vmid" ]] && continue
      slug="$(echo "$name" | tr -c 'A-Za-z0-9_' '_' | sed 's/__*/_/g; s/^_//; s/_$//')"
      echo "import {"
      echo "  to = proxmox_virtual_environment_container.${slug}"
      echo "  id = \"${PVE_NODE_NAME}/${vmid}\""
      echo "}"
      echo ""
    done <<<"$LXCS"
  fi
} >"$IMPORTS_FILE"

echo "Wrote $IMPORTS_FILE"
echo
echo "Next:"
echo "  terraform plan \\"
echo "    -var-file=/home/raman/git/home-lab/.lab/hypervisor/proxmox/values.tfvars \\"
echo "    -generate-config-out=generated.tf"
