#!/usr/bin/env bash
#
# Discovers existing OPNsense configuration via the API and writes
# `import { ... }` blocks for everything we want to bring under Terraform.
#
# Coverage (initial): firewall rules, aliases, NAT, DHCP scopes, Unbound DNS
# overrides, WireGuard. Extend as the provider grows.
#
# Usage:
#   ./scripts/generate-imports.sh
#
# Reads endpoint + creds from .lab/network/opnsense/values.tfvars.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(cd "$MODULE_DIR/../.." && pwd)"
TFVARS="$REPO_ROOT/.lab/network/opnsense/values.tfvars"
IMPORTS_FILE="$MODULE_DIR/imports.tf"

if [[ ! -f "$TFVARS" ]]; then
  echo "Missing tfvars: $TFVARS" >&2
  exit 1
fi

# Parse the tfvars (simple key = "value" extractor, good enough for this file).
URI=$(awk -F'"' '/^opnsense_uri/ {print $2}' "$TFVARS")
KEY=$(awk -F'"' '/^opnsense_api_key/ {print $2}' "$TFVARS")
SECRET=$(awk -F'"' '/^opnsense_api_secret/ {print $2}' "$TFVARS")

if [[ -z "$URI" || -z "$KEY" || -z "$SECRET" || "$KEY" == "CHANGE_ME" ]]; then
  echo "Endpoint or API key not set in $TFVARS" >&2
  exit 1
fi

CURL=(curl -sk -u "$KEY:$SECRET" -H "Accept: application/json")

api() {
  local path="$1"
  "${CURL[@]}" "${URI%/}/api/$path"
}

emit_block() {
  local resource="$1" addr="$2" id="$3"
  cat <<EOF
import {
  to = $resource.$addr
  id = "$id"
}

EOF
}

slug() {
  # Convert any string to a TF-safe identifier
  echo "$1" | tr -c 'A-Za-z0-9_' '_' | sed 's/__*/_/g; s/^_//; s/_$//'
}

{
  echo "// Generated by scripts/generate-imports.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "// OPNsense: $URI"
  echo

  # ---- Firewall aliases ----
  # GET /firewall/alias/get returns { alias: { aliases: { alias: { <uuid>: {...} } } } }
  ALIASES_JSON="$(api 'firewall/alias/get' || true)"
  if [[ -n "$ALIASES_JSON" ]]; then
    echo "# firewall aliases"
    echo "$ALIASES_JSON" \
      | jq -r '.alias.aliases.alias // {} | to_entries[] | "\(.key)\t\(.value.name)"' 2>/dev/null \
      | while IFS=$'\t' read -r uuid name; do
          [[ -z "$uuid" ]] && continue
          emit_block "opnsense_firewall_alias" "$(slug "$name")" "$uuid"
        done
    echo
  fi

  # ---- Filter (firewall) rules ----
  RULES_JSON="$(api 'firewall/filter/get' || true)"
  if [[ -n "$RULES_JSON" ]]; then
    echo "# firewall rules"
    echo "$RULES_JSON" \
      | jq -r '.filter.rules.rule // {} | to_entries[] | "\(.key)\t\(.value.description // "rule_\(.key[0:8])")"' 2>/dev/null \
      | while IFS=$'\t' read -r uuid desc; do
          [[ -z "$uuid" ]] && continue
          emit_block "opnsense_firewall_filter" "$(slug "$desc")" "$uuid"
        done
    echo
  fi

  # ---- NAT (outbound + port forward) ----
  NAT_JSON="$(api 'firewall/source_nat/get' || true)"
  if [[ -n "$NAT_JSON" ]]; then
    echo "# source NAT rules"
    echo "$NAT_JSON" \
      | jq -r '.snat.rules.rule // {} | to_entries[] | "\(.key)\t\(.value.description // "snat_\(.key[0:8])")"' 2>/dev/null \
      | while IFS=$'\t' read -r uuid desc; do
          [[ -z "$uuid" ]] && continue
          emit_block "opnsense_firewall_nat" "$(slug "$desc")" "$uuid"
        done
    echo
  fi

  # ---- Unbound DNS host overrides ----
  UNBOUND_JSON="$(api 'unbound/settings/get' || true)"
  if [[ -n "$UNBOUND_JSON" ]]; then
    echo "# Unbound host overrides"
    echo "$UNBOUND_JSON" \
      | jq -r '.unbound.hosts // {} | to_entries[] | "\(.key)\t\(.value.hostname // "host")_\(.value.domain // "lan")"' 2>/dev/null \
      | while IFS=$'\t' read -r uuid name; do
          [[ -z "$uuid" ]] && continue
          emit_block "opnsense_unbound_host_override" "$(slug "$name")" "$uuid"
        done
    echo
  fi

  # ---- WireGuard ----
  WG_JSON="$(api 'wireguard/server/get' || true)"
  if [[ -n "$WG_JSON" ]]; then
    echo "# WireGuard servers"
    echo "$WG_JSON" \
      | jq -r '.server.servers.server // {} | to_entries[] | "\(.key)\t\(.value.name // "wg")"' 2>/dev/null \
      | while IFS=$'\t' read -r uuid name; do
          [[ -z "$uuid" ]] && continue
          emit_block "opnsense_wireguard_server" "$(slug "$name")" "$uuid"
        done
    echo
  fi
} >"$IMPORTS_FILE"

echo "Wrote $IMPORTS_FILE"
echo
echo "Next:"
echo "  terraform plan \\"
echo "    -var-file=$TFVARS \\"
echo "    -generate-config-out=generated.tf"
