---
- name: Install Default K3S resources
  community.general.terraform:
    project_path: "terraform/"
    state: present
    force_init: true
    complex_vars: true
    variables:
      kube_config: "{{ kube_config }}"
      kube_host: "{{ kube_host }}"
      kube_insecure: "{{ kube_insecure }}"
      lb_iprange: "{{ lb_iprange }}"
      domain: "{{ domain }}"
      versions:
        kube_dash: "v2.7.0"
      truenas:
        host: "{{ truenas_host }}"
        port: 80
        pool: "{{ truenas_k3s_pool }}"
        apikey: "{{ truenas_api_key }}"
