locals {
  versions = {
    charts = {
      searxng    = "1.1.4"
      n8n        = "1.24.2"
      forgejo    = "17.0.0"
      prometheus = "29.2.1"
      loki       = "7.0.0"
      tempo      = "1.24.4"
      pyroscope  = "2.0.1"
      grafana    = "10.5.15"
      alloy      = "1.8.0"
      headlamp   = "0.42.0"
    }
    images = {
      n8n                  = "2.27.5"
      searxng              = "2026.6.30-d115c61a7"
      joplin               = "3.6.1"
      listmonk             = "v6.1.0"
      postiz               = "v2.21.8"
      plausible            = "v3.2.0"
      visitor_badge        = "v1.2.0"
      visitor_badge_backup = "v1.2.0"
      dovecot              = "2.3.21.1"
      spampd               = "v2.70.0-rc.1"
      spamassassin         = "latest"
      crawl4ai             = "0.9.0"
      static_site          = "latest"
      bind9                = "latest"
      blog_feature_post    = "v1.0.2"
      blog_oauth_provider  = "latest"
      vaultwarden          = "latest"
      vaultwarden_nginx    = "stable-alpine-slim"
      postfixadmin         = "4.0.1-apache"
      graphite_exporter    = "latest"
      sonarr               = "latest"
      radarr               = "latest"
      prowlarr             = "latest"
      metube               = "2026.04.28"
      jellyseerr           = "latest"
      flaresolverr         = "latest"
      redis                = "8-alpine"
      busybox              = "latest"
      cloudflared          = "2026.3.0"
      smtp_relay           = "latest"
      pihole               = "latest"
      cloudbeaver          = "25.0.1"
      temporal_server      = "1.28.1"
      temporal_ui          = "2.34.0"
      elasticsearch        = "7.17.27"
    }
  }
}
