#!/usr/bin/env bash
# Migrate Proxmox resources from .lab/hypervisor/proxmox/terraform.tfstate
# into the kubernetes-backed setup-state and deployment-state secrets via
# `import {}` blocks (TF 1.5+).
#
# Why import (not state mv): import re-reads each VM/LXC from the live
# Proxmox API, so the resulting state reflects current reality. Drift
# between config and live VMs shows up immediately in the next `plan`.
#
# What this script does:
#   1. Writes two _imports.tf files (one in setup/k3s/, one in deployment/)
#      containing `import {}` blocks for each Proxmox resource.
#   2. Stops. It does NOT run `terraform apply`.
#
# You then:
#   - terraform -chdir=setup/k3s  init
#   - terraform -chdir=setup/k3s  plan -var-file=$PWD/.lab/setup/k3s/values.tfvars
#     Expect: "Plan: N to import, 0 to add, 0 to change, 0 to destroy."
#     If anything shows "to add" or "to change" beyond the imports themselves,
#     STOP and reconcile config vs. Proxmox reality before applying.
#   - terraform -chdir=setup/k3s  apply -var-file=...   # only after plan is clean
#   - Same for deployment/ tree.
#
# After apply succeeds on both trees:
#   - rm setup/k3s/_imports.tf deployment/_imports.tf       (import blocks are one-shot)
#   - rm -rf .lab/hypervisor/                               (old state no longer needed)
#
# Rollback: import is read-only on Proxmox. If you change your mind before
# `apply`, just delete the _imports.tf files and nothing happened.
#
# CAVEAT: `proxmox_virtual_environment_file.forgejo_runner_user_data` (the
# cloud-init snippet) is NOT importable in the bpg provider — file resources
# upload content, they don't "exist" in a way Terraform can import. The
# script omits its import block. On first apply, Terraform will re-upload
# the file with the same content; the runner VM is unaffected because it
# already consumed the cloud-init data at boot.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
PVE_NODE="proxmox"   # matches pve_node_name in values.tfvars

# ---- setup/proxmox/ tree: k3s VMs + Debian template ---------------------

cat > "${REPO}/setup/proxmox/_imports.tf" <<EOF
# Generated by scripts/migrate-hypervisor-state.sh.
# Delete this file after a successful apply.
#
# Each block tells Terraform: "the resource at <to> already exists in
# Proxmox as <id>; import it instead of trying to create it."

import {
  to = module.vms.module.k3s_1.proxmox_virtual_environment_vm.this
  id = "${PVE_NODE}/4000"
}

import {
  to = module.vms.module.k3s_node_1.proxmox_virtual_environment_vm.this
  id = "${PVE_NODE}/4001"
}

import {
  to = module.templates.module.debian_cloud.proxmox_virtual_environment_vm.this
  id = "${PVE_NODE}/90000"
}
EOF

# ---- deployment/ tree: everything else ----------------------------------

cat > "${REPO}/deployment/_imports.tf" <<EOF
# Generated by scripts/migrate-hypervisor-state.sh.
# Delete this file after a successful apply.

# --- databases (LXCs) -----------------------------------------------------

import {
  to = module.databases.module.clickhouse_1.proxmox_virtual_environment_container.this
  id = "${PVE_NODE}/204"
}

import {
  to = module.databases.module.etcd_1.proxmox_virtual_environment_container.this
  id = "${PVE_NODE}/200"
}

import {
  to = module.databases.module.pg_1.proxmox_virtual_environment_container.this
  id = "${PVE_NODE}/202"
}

import {
  to = module.databases.module.pg_2.proxmox_virtual_environment_container.this
  id = "${PVE_NODE}/203"
}

# --- dev (VMs) ------------------------------------------------------------

import {
  to = module.dev.module.ai_dev.proxmox_virtual_environment_vm.this
  id = "${PVE_NODE}/10008"
}

import {
  to = module.dev.module.spampd_dev.proxmox_virtual_environment_vm.this
  id = "${PVE_NODE}/10006"
}

import {
  to = module.dev.module.talocity.proxmox_virtual_environment_vm.this
  id = "${PVE_NODE}/10007"
}

# --- gateways (LXCs under resources/) -------------------------------------

import {
  to = module.gateways.module.haproxy_1.proxmox_virtual_environment_container.this
  id = "${PVE_NODE}/2002"
}

import {
  to = module.gateways.module.private_gateway.proxmox_virtual_environment_container.this
  id = "${PVE_NODE}/2001"
}

import {
  to = module.gateways.module.public_gateway.proxmox_virtual_environment_container.this
  id = "${PVE_NODE}/2000"
}

# --- media (LXCs) ---------------------------------------------------------

import {
  to = module.media_proxmox.module.jellyfin.proxmox_virtual_environment_container.this
  id = "${PVE_NODE}/1001"
}

import {
  to = module.media_proxmox.module.qbittorrent.proxmox_virtual_environment_container.this
  id = "${PVE_NODE}/1002"
}

# --- code: Forgejo Actions runner VM -------------------------------------

import {
  to = module.code.module.forgejo_runner_1.proxmox_virtual_environment_vm.this
  id = "${PVE_NODE}/6000"
}

# --- one-offs split into apps/ --------------------------------------------

import {
  to = module.apps.module.nextcloud.module.nextcloud.proxmox_virtual_environment_container.this
  id = "${PVE_NODE}/9000"
}

import {
  to = module.apps.module.home-assistant.module.home_assistance.proxmox_virtual_environment_vm.this
  id = "${PVE_NODE}/7000"
}

import {
  to = module.apps.module.wordpress.module.wp_serverless.proxmox_virtual_environment_vm.this
  id = "${PVE_NODE}/5000"
}

# NOTE: proxmox_virtual_environment_file.forgejo_runner_user_data is NOT
# imported — bpg/proxmox doesn't support file resource import. Terraform
# will re-upload the file content on first apply; the runner VM already
# consumed it at boot, so re-upload is a no-op for the running runner.
EOF

cat <<EOF

Wrote import blocks:
  ${REPO}/setup/proxmox/_imports.tf  (3 resources)
  ${REPO}/deployment/_imports.tf     (16 resources)

Next:
  terraform -chdir=${REPO}/setup/proxmox init -backend-config=backend.local.hcl
  terraform -chdir=${REPO}/setup/proxmox plan -var-file=${REPO}/.lab/setup/proxmox/values.tfvars

  # Expect: "Plan: 3 to import, 0 to add, 0 to change, 0 to destroy."
  # If you see additional add/change/destroy lines for the imported resources,
  # STOP. Reconcile config vs. Proxmox reality before applying.

  terraform -chdir=${REPO}/setup/proxmox apply -var-file=${REPO}/.lab/setup/proxmox/values.tfvars

  terraform -chdir=${REPO}/deployment init -backend-config=backend.local.hcl
  terraform -chdir=${REPO}/deployment plan -var-file=${REPO}/.lab/deployment/values.tfvars
  # Expect: "Plan: 16 to import, 1 to add, 0 to change, 0 to destroy."
  # The "1 to add" is the forgejo_runner_user_data file resource (re-upload).
  terraform -chdir=${REPO}/deployment apply -var-file=${REPO}/.lab/deployment/values.tfvars

After both applies succeed:
  rm ${REPO}/setup/proxmox/_imports.tf ${REPO}/deployment/_imports.tf
  rm -rf ${REPO}/.lab/hypervisor/

If something looks wrong:
  rm ${REPO}/setup/proxmox/_imports.tf ${REPO}/deployment/_imports.tf
  Import is read-only; nothing on Proxmox or in your cluster state changed.
EOF
