FROM alpine:3.18.2

ENV SSH_KEY_NAME=id_rsa
ENV REMOTE_PORT=
ENV PROXY_SSH_USER=dev
ENV PROXY_HOST=
ENV PROXY_SSH_PORT=22

RUN apk add --no-cache bash autossh

COPY startup.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

VOLUME [ "/config" ]

ENTRYPOINT [ "/docker-entrypoint.sh" ]
