FROM nginx:alpine

ENV SSH_KEY_NAME=id_rsa
ENV REMOTE_PORT=
ENV PROXY_SSH_USER=dev
ENV PROXY_HOST=
ENV PROXY_SSH_PORT=22

RUN apk add --no-cache bash autossh

COPY startup.sh /docker-entrypoint.d/startup.sh

COPY config/nginx/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /config/nginx/default.d && mkdir -p /config/nginx/conf.d

RUN chmod +x /docker-entrypoint.d/startup.sh

VOLUME [ "/config" ]
