---
- name: Destory resources
  hosts: localhost
  tags:
    - resources
  roles:
    - role: reset/resources

- name: Destory K3s Cluster and configuration
  hosts: k3s_cluster
  tags:
    - setup
  roles:
    - role: reset/k3s
