name: dovecot CI

on:
  push:
    paths:
      - apps/dovecot/**
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          # VERSION=$(grep "^FROM " apps/dovecot/Dockerfile | awk -F':' '{print $2}' | awk '{print $1}')
          VERSION=2.3.21.1
          echo "::set-output name=tags::ramank775/dovecot:$VERSION"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: apps/dovecot
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.extract_version.outputs.tags }}